export const INTERVIEW_EMAIL_SIGN_UP = 'INTERVIEW_EMAIL_SIGN_UP';
export const INTERVIEW_EMAIL_SIGN_UP_REQUEST = 'INTERVIEW_EMAIL_SIGN_UP_REQUEST';

export const OTP_REQUEST = "OTP_REQUEST";
export const OTP_SUCCESS = "OTP_SUCCESS";
export const OTP_FAILED = "OTP_FAILED";