export const INTERVIEW_EMAIL_SIGN_UP = "INTERVIEW_EMAIL_SIGN_UP";
export const INTERVIEW_EMAIL_SIGN_UP_REQUEST =
  "INTERVIEW_EMAIL_SIGN_UP_REQUEST";
export const INTERVIEW_EMAIL_SIGN_UP_FAILURE =
  "INTERVIEW_EMAIL_SIGN_UP_FAILURE";
export const INTERVIEW_EMAIL_SIGN_UP_ERROR = "INTERVIEW_EMAIL_SIGN_UP_ERROR";

export const ADD_CANDIDATE_REQUEST = "ADD_CANDIDATE_REQUEST";
export const ADD_CANDIDATE_SUCCESS = "ADD_CANDIDATE_SUCCESS";
export const ADD_CANDIDATE_FAILURE = "ADD_CANDIDATE_FAILURE";

export const OTP_REQUEST = "OTP_REQUEST";
export const OTP_SUCCESS = "OTP_SUCCESS";
export const OTP_FAILED = "OTP_FAILED";
export const OTP_ERROR = "OTP_ERROR";

export const QUESTIONS_SUCCESS = "QUESTIONS_SUCCESS";
export const QUESTIONS_FAILURE = "QUESTIONS_FAILURE";

export const CALL_HELP_REQUEST = "CALL_HELP_REQUEST";
export const CALL_HELP_SUCCESS = "CALL_HELP_SUCCESS";
export const CALL_HELP_FAILURE = "CALL_HELP_FAILURE";

export const SUBMIT_TEST_REQUEST = "SUBMIT_TEST_REQUEST";
export const SUBMIT_TEST_SUCCESS = "SUBMIT_TEST_SUCCESS";
export const SUBMIT_TEST_FAILURE = "SUBMIT_TEST_FAILURE";
