# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HRrecruit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HRrecruit
  pod 'AppCenter/Crashes', '~> 1.6.1'
  pod 'AppCenter/Analytics', '~> 1.6.1'
  pod 'AppCenterReactNativeShared', '~> 1.6.0'
  pod 'Appboy-iOS-SDK', '~> 3.0.2'
  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker`
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  platform :ios, '9.0'
  pod 'react-native-version-number', :path => '../node_modules/react-native-version-number'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'HRrecruitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'HRrecruit-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HRrecruit-tvOS

  target 'HRrecruit-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
