# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HRrecruit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HRrecruit
  pod 'AppCenter/Crashes', '~> 1.6.1'
  pod 'AppCenter/Analytics', '~> 1.6.1'
  pod 'AppCenterReactNativeShared', '~> 1.6.0'
  pod 'Appboy-iOS-SDK', '~> 3.0.2'
  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker`
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  platform :ios, '9.0'
  pod 'react-native-version-number', :path => '../node_modules/react-native-version-number'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  target 'HRrecruitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'HRrecruit-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HRrecruit-tvOS

  target 'HRrecruit-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
