# Uncomment the next line to define a global platform for your project
# platform :ios, ‘9.0’

target 'HRrecruit' do
  pod 'AppCenter/Crashes', '~> 1.11.0'
  pod 'AppCenter/Analytics', '~> 1.11.0'
  pod 'AppCenterReactNativeShared', '~> 1.10.0'
  pod 'Firebase/Core','4.2.0'
  pod 'Firebase/Messaging','4.2.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HRrecruit
  pod 'Appboy-iOS-SDK', '~> 3.0.2'
  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker’
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  platform :ios, ‘9.0’
  pod 'react-native-version-number', :path => '../node_modules/react-native-version-number'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'

  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTNetwork',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    ‘RCTImage’,
    'RCTLinkingIOS',
    'RCTSettings',
    'RCTVibration',
    'RCTActionSheet',
    # Add any other subspecs you want to use in your project
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  target 'HRrecruitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'HRrecruit-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HRrecruit-tvOS

  target 'HRrecruit-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
